package com.hrm.recruitment.entity;

public enum ApplicationStatus {
    PENDING_HR_CV_REVIEW,
    PENDING_TECH_CV_REVIEW,
    PENDING_INTERVIEW_1,
    PENDING_INTERVIEW_2,
    PENDING_HR_OFFER,
    PENDING_OFFER_APPROVAL,
    OFFER_INTERNALLY_APPROVED,
    OFFER_SENT,
    OFFER_ACCEPTED,
    REJECTED,
    TALENT_POOL,
    WITHDRAWN,
    OFFER_DECLINED,
    OFFER_EXPIRED,
    OFFER_REVOKED
}
