spring:
  config:
    import: optional:file:.env[.properties], optional:file:./Backend/.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000
  gemini:
    api-key: ${GEMINI_API_KEY}
    model: gemini-3.6-flash
    base-url: https://generativelanguage.googleapis.com/v1beta
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
  cors:
    allowed-origins: http://localhost:5173,http://localhost:5174
  face:
    similarity-threshold: 0.85
  cv-extraction:
    confidence-threshold: 0.7

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always
    include-binding-errors: always


payroll:
  late-free-times: 1
  late-penalty-percent: 0.3
  late-percent-tier-max-times: 3
  late-4th-time-days-deducted: 0.5
  late-5th-plus-days-deducted: 1.0
  half-day-leave-deducted: 0.5
  normal-leave-days-per-month: 1
  special-wfh-leave-days-per-month: 1
  overtime-multiplier: 1.5
  insurance:
    bhxh-percent: 0.08
    bhyt-percent: 0.015
    bhtn-percent: 0.01
  tax:
    personal-deduction: 15500000
    dependent-deduction: 6200000
